---
title: "Know what you don't know: Embracing state uncertainty in disease-structured multistate models"
author: Matthijs Hollanders$^1$* & J. Andrew Royle$^2$
format:
  pdf:
    toc: false
    keep-tex: true
editor_options:
  chunk_output_type: console
execute:
  include: false
bibliography: multievent.bib
nocite: |
  hollanders2022b, 
csl: methods-in-ecology-and-evolution.csl
geometry: margin = 1in
linestretch: "2"
header-includes: |
  \usepackage{titling}
  \pretitle{\begin{flushleft}\Large\bfseries}
  \posttitle{\end{flushleft}}  
  \preauthor{\begin{flushleft}\large}
  \postauthor{\end{flushleft}} 
  \usepackage{lineno}
  \linenumbers
  \usepackage{blkarray}
  \usepackage{multirow}
  \usepackage{float}
  \floatplacement{figure}{H}
  \usepackage[bf]{caption}
  \newcommand{\beginsupplement}{
    \setcounter{table}{0} 
    \renewcommand{\thetable}{S\arabic{table}}
    \setcounter{figure}{0} 
    \renewcommand{\thefigure}{S\arabic{figure}}}
---

$^1$Faculty of Science and Engineering, Southern Cross University, Lismore, New South Wales 2480, Australia, matthijs.hollanders\@gmail.com, corresponding author\
$^2$U.S. Geological Survey, Patuxent Wildlife Research Center, Laurel, Maryland 20708--4017 USA 

\*Corresponding author, [matthijs.hollanders\@gmail.com](mailto:matthijs.hollanders@gmail.com){.email}

 

Running headline: State uncertainty in multistate models

```{r}
options(scipen = 999, digits = 2)

library(tidyverse)
library(HDInterval)
me <- read_csv('mcmc-samples/MEdraws.csv')
ms <- read_csv('mcmc-samples/MSdraws.csv')
me.nofp <- read_csv('mcmc-samples/MEdraws-dellam0.csv')
```

\newpage

# Abstract

1.  Hidden Markov models (HMMs) are broadly applicable hierarchical models that derive their utility from separating state processes from observation processes yielding the data. Multistate models such as mark-recapture and dynamic multistate occupancy models are HMMs that are frequently used in ecology. In their early formulations, states, such as pathogen infection status, were assumed to be perfectly observed without ambiguity. However, state uncertainty is a pervasive feature of many ecological studies, and multievent models were developed to explicitly account for it.

2.  We developed a novel extended multievent mark-recapture model that incorporates state uncertainty at multiple levels of detection. Using a disease-structured example, both false-negative and false-positive state assignment errors are modeled at two levels of state assignment---the pathogen sampling process and the diagnostic process that samples are subjected to. We additionally describe methods to jointly model infection intensity to integrate heterogeneity in ecological parameters, such as survival, infection dynamics, and the pathogen detection processes. We provide code to simulate and analyze datasets with various underlying ecological processes and fit our model to a mark-recapture dataset of *Mixophyes fleayi* (Fleay's barred frog) infected with the amphibian chytrid fungus (*Batrachochytrium dendrobatidis*, *Bd*).

3.  In our case study, we found evidence for various state assignment errors: the sampling protocol performed poorly in detecting *Bd*, pathogen detection was highly dependent on infection intensity, and false-positives were non-negligible. Incorporating state uncertainty yielded significantly higher estimates of infection prevalence and 4--5 times lower rates of infection state transitions compared to those obtained from a traditional multistate model.

4.  Our results highlight that incorporating state assignment errors improves inference on the ecological state process, especially when sensitivity and specificity of the state assignment processes are low. The general model structure can be applied to other HMMs, providing a foundation for modeling state uncertainty in related models.

**Keywords:** hidden Markov model, state uncertainty, multievent, mark-recapture, Bayesian, hierarchical model, *Batrachochytrium dendrobatidis*

\newpage

# Introduction

Biologists seek to understand systems at all levels of the phenomenological hierarchy, which can often be described by changes in underlying states over time. Empirical studies are conducted to describe biological state processes and dynamics, but these are usually subject to imperfect observation, especially in field settings. States are defined as *latent* when they can not be observed and consequently not directly inferred from observed data. Hidden Markov models (HMMs) are a diverse class of hierarchical models that are able to disentangle the latent state process from the observation process yielding the data, facilitating inference on processes from the individual to the community level [@mcclintock2020; @glennie2022]. Well-known examples of ecological HMMs include mark-recapture, occupancy, and *N*-mixture models, where the observation process is modeled conditional on the underlying latent ecological states. In the most basic mark-recapture model, the ecological process describes individual survival after first capture, and the observation process consists of recapture probabilities conditional on an individual being alive. This model can be thought of as a HMM with two latent ecological states and two observed states. The latent ecological state "alive" is partially observed (an individual is only known to be alive when it is captured) and the ecological state "dead" is completely unobserved (an individual is not known to be dead when it is not recaptured). The two observed states are then "recaptured" and "not recaptured".

Multistate extensions of mark-recapture models, often referred to as Arnason-Schwarz models, are HMMs with more than two ecological states [@arnason1972; @arnason1973; @schwarz1993]. Specifically, the dead state remains and the alive state is decomposed into several possible states---examples include pathogen infection status (infected/uninfected) and breeding status (breeder/non-breeder). In addition to estimating state-specific survival and recapture probabilities, these models can estimate the probabilities of transitioning between ecological states. Examples of state transitions include gaining and clearing pathogen infections (infection dynamics) and transitioning from non-breeder to breeder. Depending on the model specification, individuals could freely transition between states (e.g., hosts repeatedly gain and clear pathogens), or transitions can occur in one direction (e.g., individuals can only transition from subadult to breeder).

Traditional multistate models assumed that states are correctly assigned when individuals are observed [@lebreton2002; @conn2009]. For example, breeding status may be ascertained based on observing individuals with eggs or offspring, and age may be determined by body size. However, depending on the nature of the states, this assumption is often significantly violated. In a disease context, for instance, infection status of individuals is frequently based on samples (e.g., blood, feces, swabs), which in turn are subjected to a diagnostic procedure (e.g., histology, Polymerase Chain Reaction [PCR]), both of which may be subject to imperfect pathogen detection [@mcclintock2010; @direnzo2018]. State assignment errors can take two forms: uncertain and incorrect state assignment [@conn2009; @mcclintock2010]. In the former, investigators do not assign a specific state other than an individual being alive because of uncertainty surrounding the state classification. In the latter, investigators do assign a state based on some criteria, but that assignment fails to reflect the true underlying state.

Multievent models were developed to account for state misclassification in mark-recapture models [@pradel2005]. Instead of unambiguously assigning a state based on some observation, observations are categorised as "events" which reflect uncertainty about the underlying ecological state. Investigators do not claim to know the state of an observed individual, but information is collected about that individual which facilitates probabilistically resolving it. For example, in disease studies, one can model the event of not detecting a pathogen on a sample collected at capture (false-negative) or the possibility of getting a false-positive detection. Moreover, multiple levels of uncertainty in state assignment may exist: in a disease context, both the sampling and the diagnostic processes that samples are subjected to may contain errors [@lachish2012; @miller2012; @direnzo2018]. Note that false-negative state assignment errors in a disease context are expected to be dependent on infection intensity, where errors are more likely to occur when pathogen loads are low [@direnzo2018]. Ignoring state misclassification is expected to have considerable influence on the parameters of the ecological process [@mcclintock2010], especially on the relative abundance of specific states (e.g., infection prevalence) and transitions between them.

Modeling false-negatives is routine in ecological models: indeed, imperfect detection of individuals and species lies at the heart of statistical ecology. False-positives have received much less attention, but even low probabilities (1%) can significantly bias parameter estimates [@royle2006; @mcclintock2010a; @miller2011]. False-positives in a disease context can result from contamination during the sampling and diagnostic processes, low specificity, and other mechanisms, but also routinely occur in other data types frequently modeled using HMMs (e.g., data derived from citizen science programs and machine learning) [@royle2006]. Modeling false-positives presents some challenges, such as multimodal solutions inherent to finite mixture models. Incorporating prior information, applying reasonable constraints on parameters, employing multiple detection methods, and including covariates in the detection process can often remedy this issue [@mcclintock2010a; @miller2011].

In this paper, we describe a novel extension to multievent mark-recapture models incorporating imperfect state assignment (both false-negatives and false-positives) at two levels, using a disease-structured example. We demonstrate that by expanding traditional capture histories (observed state of an individual during a survey) to the level of replicate diagnostic runs from collected samples, state misclassification is fully accounted for in modeling the ecological process of interest. We show how the quantities of pathogen DNA detected in these replicate diagnostic runs can be used to estimate infection intensities of samples and individuals, which can serve as predictors in load-dependent heterogeneity functions of pathogen detection and survival. Although our model describes a mark-recapture model, the structure can apply to HMMs more generally, such as dynamic multistate occupancy models, where state uncertainty may play a significant role. We provide code to simulate data and analyse models with two underlying ecological processes [Arnason-Schwarz and Jolly-Seber, @jolly1965; @seber1965], in both discrete- and continuous-time, to aid researchers with analysis and to provide a basis for exploring model performance. Finally, we illustrate the use of our model with a dataset of juvenile *Mixophyes fleayi* (Fleay's barred frog), an Australian narrow-range endemic rainforest species, to investigate post-metamorphic susceptibility to the amphibian chytrid fungus *Batrachochytrium dendrobatidis* (*Bd*).

\newpage

# Materials and methods

## Extended multievent model

We describe a multievent model accounting for two levels of infection state uncertainty, specifically the sampling and diagnostic processes involved in the detection and quantification of pathogen DNA on hosts. We model at the level of replicated diagnostic runs of partially replicated samples collected from individuals during robust design mark-recapture surveys, i.e., multiple secondary surveys during primary occasions of assumed closure [@pollock1982]. Each time an individual is captured during successive secondary surveys, its unique identity is recorded (or it will be marked if it is new to the study) and a sample is collected to inform its infection status. Both infection status and infection intensity obtained from diagnostic runs are used as data: the former to construct a capture history, and the latter as auxiliary data to estimate sample and individual infection intensities (which serve to model heterogeneity in pathogen detection probabilities and parameters in the ecological process). We provide (BUGS) code to simulate and analyze models with two underlying ecological processes (*Supporting Information Appendix S1--2*).

### Ecological process

Our demonstration, using frogs and the amphibian chytrid fungus *Bd* as a motivating example, presents the ecological process with an Arnason-Schwarz model (@tbl-parameters), but the model is readily fit with alternative underlying state processes like the Jolly-Seber. Individuals can be in one of three ecological states ($z$): (1) alive and *Bd*--, (2) alive and *Bd*+, and (3) dead. At first capture, the latent ecological state of individual $i$ is modeled as a categorical random variable, where $\pi$ is the probability of being infected with *Bd*:

```{=tex}
\begin{center}
  \begin{blockarray}{l *{3}{c}}
    & Alive, \textit{Bd}-- & Alive, \textit{Bd}+ & Dead \\
    \begin{block}{l ( *{3}{c} )}
      $z_{i,\text{first}_{i}} \sim \operatorname{Categorical}$ & $1-\pi$ & $\pi$ & $0$ \\
  \end{blockarray}
\end{center}
```
After initial capture, the ecological process consists of survival and state transitions, which here describe the *Bd* infection dynamics. For each occasion after an individual's first capture, the ecological state of individual $i$ during primary occasion $t$ (columns) is modeled as conditional on its state during occasion $t-1$ as a first-order Markov process (rows) [@kery2012b]:

```{=tex}
\begin{center}
  \begin{blockarray}{l *{3}{c} l l}
    & \BAmulticolumn{3}{c}{$z_{it}$} & & \\
    & Alive, \textit{Bd}-- & Alive, \textit{Bd}+ & Dead & & \\
    \begin{block}{l ( *{3}{c} ) l l}
      \multirow{3}{*}{$z_{it}|z_{it-1} \sim \operatorname{Categorical}$} & $\phi_{1}(1-\psi_{12})$ & $\phi_{1}\psi_{12}$ & $1-\phi_{1}$ & Alive, \textit{Bd}-- & \multirow{3}{*}{$z_{it-1}$} \\
      & $\phi_{2}\psi_{21}$ & $\phi_{2}(1-\psi_{21})$ & $1-\phi_{2}$ & Alive, \textit{Bd}+ & \\
      & $0$ & $0$ & $1$ & Dead & \\
  \end{blockarray}
\end{center}
```
where $\phi_1$ and $\phi_2$ are the survival probabilities of uninfected and infected individuals, respectively, and $\psi_{12}$ and $\psi_{21}$ are the probabilities of gaining and clearing infections, respectively (@tbl-parameters). This discrete-time formulation assumes that state transitions occur at most once during a primary occasion interval, and this construction cannot account for unequal time intervals between primary occasions [@glennie2022].

Alternatively, the ecological process can be expressed in continuous-time with a transition *rate* matrix (TRM) instead of a transition *probability* matrix (TPM) shown above. Since state transitions like survival and infection dynamics occur instantaneously in continuous-time, hazard rates are more appropriate than probabilities to model these processes, in particular when intervals between primary occasions are unequal [@miller2008; @conn2012; @ergon2018; @glennie2022; @mews2022]. Using matrix exponentials, the TPM can be computed from the TRM with the ecological process expressed as $z_{it}|z_{it-1} \sim \operatorname{Categorical}(e^{\mathbf{TRM}\tau})$, where $\tau$ is a vector of primary occasion time intervals (expressed in units of time expected to see at most one state transition), and

```{=tex}
\begin{center}
  \begin{blockarray}{l *{3}{c} l l}
    & \BAmulticolumn{3}{c}{$z_{it}$} & & \\
    & Alive, \textit{Bd}-- & Alive, \textit{Bd}+ & Dead & & \\
    \begin{block}{l ( *{3}{c} ) l l}
      \multirow{3}{*}{$\mathbf{TRM} = $} & $-(\psi_{12} + \phi_1)$ & $\psi_{12}$ & $\phi_1$ & Alive, \textit{Bd}-- & \multirow{3}{*}{$z_{it-1}$} \\
      & $\psi_{21}$ & $-(\psi_{21} + \phi_{2})$ & $\phi_2$ & Alive, \textit{Bd}+ & \\
      & $0$ & $0$ & $0$ & Dead & \\
  \end{blockarray}
\end{center}
```
where $\phi_1$ and $\phi_2$ are the mortality hazard rates of uninfected and infected individuals, respectively, and $\psi_{12}$ and $\psi_{21}$ are the hazard rates of gaining (force-of-infection) and clearing infections, respectively [@conn2012] (@tbl-parameters). We demonstrate the continuous-time approach in *Supporting Information Appendix S1* and the discrete-time approach in *Supporting Information Appendix S2*. Note that all parameters can be estimated as functions of covariates with appropriate link functions (e.g., logit-link for probabilities and log-link for hazard rates), which for the continuous-time formulation requires the assumption that covariates (and rates) are piecewise constant over time [@mews2022]. Next, we show the observation process, where the mark-recapture surveys follow the robust design. See *Discussion* and *Supporting Information Appendix S3* for issues arising with fitting this model with single surveys.

### Observation process

The observation process consists of the individual detection (recapture) process and the sampling process employed to detect *Bd*. When mark-recapture surveys are conducted following the robust design, several secondary surveys are conducted during multiple primary occasions of assumed closure (i.e., no births, deaths, immigration, emigration, and change of infection status or intensity) [@pollock1982]. Samples are collected during each capture, including recaptures during successive secondaries. The sampling process can be modeled in an occupancy-like fashion (multiple sample units with replicated measurements), where individuals represent sites and samples represent repeat visits [@mackenzie2002]. Multiple samples are thus only collected for individuals captured over successive secondaries within a primary, which is sufficient to estimate the pathogen detection probabilities if at least some individuals are recaptured over successive secondaries.

Possible observed states ($o$) are (1) seen/recaptured with sample *Bd*--, (2) seen/recaptured with sample *Bd*+, and (3) not seen/recaptured. Note that the first two states are latent because we do not claim to know the true infection status of the sample. The observed state of individual $i$, primary occasion $t$, and (sample collected during) secondary survey $k$ (columns) is modeled conditional on the individual's ecological state (rows):

```{=tex}
\begin{center}
  \begin{blockarray}{l *{3}{c} l l}
    & \BAmulticolumn{3}{c}{$o_{itk}$} & & \\
    & Seen, sample \textit{Bd}-- & Seen, sample \textit{Bd}+ & Not seen & & \\
    \begin{block}{l ( *{3}{c} ) l l}
    \multirow{3}{*}{$o_{itk}|z_{it} \sim \operatorname{Categorical}$} & $p_{1}(1-\delta_{21})$ & $p_{1}\delta_{21}$ & $1-p_{1}$ & Alive, \textit{Bd}-- & \multirow{3}{*}{$z_{it}$} \\
    & $p_{2}(1-\delta_{22})$ & $p_{2}\delta_{22}$ & $1-p_{2}$ & Alive, \textit{Bd}+ & \\
    & $0$ & $0$ & $1$ & Dead & \\
  \end{blockarray}
\end{center}
```
Here, $p_{1}$ and $p_{2}$ are the recapture probabilities of uninfected and infected individuals, respectively; $\delta_{22}$ is the probability of detecting *Bd* on a sample from an infected individual (sampling sensitivity), where $1 - \delta_{22}$ is the false-negative probability of the sampling device; and $\delta_{21}$ is the false-positive probability, where $1 - \delta_{21}$ is the true-negative probability (sampling specificity) (@tbl-parameters). To avoid multimodal solutions that are common with modeling false-positives, reasonable constraints may be applied [e.g., $\delta_{21} < \delta_{22}$, @royle2006] or covariates can be included on the pathogen detection probability (see *Incorporating infection intensities* below) [@miller2011]. Note that the observation process for individuals during the primary occasion of first capture is slightly modified: because the model is conditioned on first capture, we constrain the capture probabilities to 1 for those secondaries within the primary that they were first captured. This can be relaxed if the model is extended to include the recruitment process, i.e., through the Jolly-Seber ecological process.

### Diagnostic process

The diagnostic process describes the replicate diagnostic runs that each sample is subjected to detect an infection. In the case of swab samples to detect *Bd*, quantitative PCR (qPCR) is typically performed in duplicate or triplicate and investigators assign individual infection status depending on the results [@hyatt2007]. To account for imperfect pathogen detection in the diagnostic process, the replicate qPCR runs can be modeled equivalently to the sampling process via an occupancy design, where samples and diagnostic runs are analogous to sites and visits, respectively. Diagnostic run states ($y$) are used to construct capture histories as data and can be in three possible states: (1) *Bd*--, (2) *Bd*+, and (3) no diagnostic run performed. The last state is only possible when the individual was not detected and therefore not sampled. We parameterize the diagnostic pathogen detection process in terms of the following parameters: $\lambda_{22}$, the probability of detecting the pathogen on an infected sample (diagnostic sensitivity), with the complementary false-negative probability $1-\lambda_{22}$; and the false-positive probability $\lambda_{21}$, with the complementary true-negative probability $1-\lambda_{21}$ (diagnostic specificity) (@tbl-parameters). The observed diagnostic run state of individual $i$, primary occasion $t$, (sample collected during) secondary survey $k$, and diagnostic run $l$ (columns) is modeled conditional on its observed state (rows):

```{=tex}
\begin{center}
  \begin{blockarray}{l *{3}{c} l l}
    & \BAmulticolumn{3}{c}{$y_{itkl}$} & & \\
    & \textit{Bd}-- & \textit{Bd}+ & No diagnostic run & & \\
    \begin{block}{l ( *{3}{c} ) l l}
    \multirow{3}{*}{$y_{itkl}|o_{itk} \sim \operatorname{Categorical}$} & $1-\lambda_{21}$ & $\lambda_{21}$ & $0$ & Seen, \textit{Bd}-- & \multirow{3}{*}{$o_{itk}$} \\
    & $1-\lambda_{22}$ & $\lambda_{22}$ & $0$ & Seen, \textit{Bd}+ & \\
    & $0$ & $0$ & $1$ & Not seen & \\
  \end{blockarray}
\end{center}
```
Thus, we have extended the traditional two-dimensional capture histories of mark-recapture models---observed state of individual $i$ during survey $t$---to four dimensions at the level of the diagnostic run $l$ of sample $k$ during primary occasion $t$ of individual $i$. In the next section, we demonstrate using the observed infection intensities in replicate diagnostic runs to estimate infection intensities of samples and individuals, and integrating these into the ecological, observation, and diagnostic processes [@direnzo2018].

### Incorporating infection intensities

The latent individual and sample infection intensities, estimated from positive diagnostic runs, can be used to model intensity-dependent heterogeneity in survival, state transition, and pathogen detection processes. Infection intensities ($m$) of individual $i$ during primary occasion $t$ are modeled as coming from a lognormal distribution:

$$m_{it} \sim \operatorname{Lognormal}(\mu, \sigma^2_\mu)$$

where $e^\mu$ and $e^{\sigma_\mu}$ are the geometric mean and standard deviation (SD), respectively, of the population infection intensities. Infection intensity values are often already log-transformed, and both normal and lognormal distributions have been used to model these transformed values of infection burdens in populations [@miller2012; @direnzo2018]. However, the lognormal (or gamma) distribution may be more appropriate given that pathogen loads are always positive and frequently right-skewed, even after log-transformation.

Since disease impact on an individual is often proportional to its infection intensity [@hollanders2022a], intensity can be included as a time-varying individual covariate on survival probabilities or mortality rates in generalised linear model (GLM)-like fashion. For example, when modeling mortality hazard rates, infection intensity can be included as predictor with a log-link function, i.e., $\operatorname{log}({\phi_2}_{it}) = \phi_\alpha + \phi_\beta m_{it}$. Additionally, the amount of pathogen DNA present on individuals greatly influences pathogen detection rates [@lachish2012; @miller2012; @direnzo2018], inducing variation which can be modeled. The probability of detecting the pathogen in the sampling protocol can be modeled as follows, where $r_\delta$ is the probability of detecting one unit (e.g., an order of magnitude on log~10~-transformed values) of pathogen DNA with a particular sampling device [@royle2003; @lachish2012]:

$${\delta_{22}}_{it} = 1 - (1 - r_\delta)^{m_{it}}$$

Infection intensities of replicate positive samples ($n$) are naturally modeled as draws from normal distributions centered on the individual infection intensities, where $\sigma_m$ describes the measurement error of the sampling protocol:

$$n_{itk} \sim \operatorname{Normal}(m_{it}, \sigma^2_m)$$

The estimated sample intensities can be used to model the pathogen detection probabilities in the diagnostic process equivalently to the sampling process, where $r_\lambda$ is the probability of detecting one unit of pathogen DNA during a diagnostic run:

$${\lambda_{22}}_{itk} = 1 - (1 - r_\lambda)^{n_{itk}}$$

Finally, the observed infection intensities in replicate diagnostic runs ($x$) are modeled as data drawn from normal distributions centered on the sample infection intensities, where $\sigma_n$ describes the measurement error of the diagnostic process:

$$x_{itkl} \sim \operatorname{Normal}(n_{itk}, \sigma^2_n)$$ Thus, the capture histories of the diagnostic states ($y$) and the respective pathogen infection intensities of positive samples ($x$) are jointly utilized as data to improve inference on pathogen impact and to correct for intensity-dependent pathogen detection.

### Model assumptions

The extended multievent model makes some assumptions in addition to those in standard multistate/multievent models (e.g., that marks are not lost and always read correctly; that sampling is instantaneous; that state transitions occur at the end of each interval; and that there is no memory of previous ecological states) [@schwarz1993; @mcclintock2020]. It is implicitly assumed that samples are collected each time an individual is encountered. In sampling schemes where this does not occur, state uncertainty can be incorporated [e.g., with the addition of an uncertain infection state, @conn2009] or $\delta_{22}$ can be fixed to 0 for individuals during those occasions. The model also requires that at least some individuals are recaptured more than once during primary occasions to estimate the sampling process. The closure assumption extends to infection status and intensity, where pathogen loads of the individual and samples are assumed to be constant between replicate samples and diagnostic runs, respectively. These assumptions can be relaxed by modeling, $r_\delta$, i.e., with a decay function, where successive samples may be expected to detect less pathogen. Additionally, our model assumes that the diagnostic pathogen detection probability of true- and false-positive samples is identical ($\lambda_{22}|(o=2|z=2) = \lambda_{22}|(o=2|z=1)$), and similarly, that the diagnostic false-positive probability of true- and false-negative samples is identical ($\lambda_{21}|(o=1|z=1) = \lambda_{21}|(o=1|z=2)$). Correspondingly, the infection intensities of true- and false-positive samples and diagnostic runs are modeled as coming from the same hyper-distributions. A possible modification would be to model true- and false-positive infection intensities from multimodal distributions, where false-positives could be expected to have lower intensities.

## Model application

### Implementation

We used Bayesian inference utilizing Markov chain Monte Carlo (MCMC) methods with NIMBLE 0.12.2 [@devalpine2017; @devalpine2022] through R 4.2.1 [@rcoreteam2022] to estimate the posterior distributions of model parameters. We used $\operatorname{Beta}(1, 1)$ priors on all probabilities, $\operatorname{Exponential}(1)$ priors for all hazard rates, and weakly informative (half-)Cauchy priors priors on the (log) population average *Bd* infection intensity ($\mu$), the effect of *Bd* on survival ($\phi_\beta$), and SD parameters. We constrained the probabilities of false-positives in the sampling and diagnostic processes to be less than the per-unit true-positive probabilities ($r$) to avoid multimodality. We used NIMBLE's default MCMC configurations. For each model, we ran 4 chains from overdispersed initial values for 10,000 iterations after discarding the first 1,000 as burn-in with a thinning rate of 4, yielding 10,000 posterior draws. Parameter estimates are reported as medians and 95% highest posterior density intervals (HPDI).

### Simulations

We conducted simulations to determine whether parameters could be recovered from simulated data for both robust design and traditional single-survey (no replicated secondary surveys) designs. To determine whether the models could recover parameters, we assessed MCMC mixing, convergence of chains, and whether posterior distributions encompassed simulation parameters. We did not systematically assess model performance over a range of parameter values due to the large number of parameters. Instead, we provided code to simulate and analyze capture histories with different underlying ecological processes (Arnason-Schwarz in continuous-time and Jolly-Seber in discrete-time) and demonstrate the validity of the model structure. We recommend practitioners conduct their own simulations, with realistic parameter values for their study systems, to assess specific model performance.

### Case study: *Mixophyes fleayi* (Fleay's barred frog)

We compared the performance of the novel extended multievent model with a traditional multistate Arnason-Schwarz model using a photographic mark-recapture dataset of juvenile *Mixophyes fleayi* (Fleay's barred frog), an endangered Australian rainforest frog [@hollanders2022b]. We conducted 14 weekly surveys on a 500-m road transect and made 386 captures of 116 unique individuals. Of those, 72% (83) were recaptured more than once, with a median of 3 captures per individual (range of 1--9). Single swab samples were collected during each capture, DNA was extracted using Prepman™ Ultra, and extracted DNA was subjected to at least two qPCR diagnostic runs using standard protocols [@hyatt2007]. The original surveying method did not include multiple secondary surveys; however, by pooling consecutive weeks into primary occasions composed of two secondary surveys each, we approximated robust design sampling. We recognize that the closure assumption was likely violated, but nevertheless use the dataset to illustrate the model given the limited reliability of swabs to detect low infection intensities [@shin2014; @direnzo2018].

We added two pseudo-surveys with missing values for the two weeks that we did not survey to maintain equal survey intervals, yielding 16 surveys to be modeled. Note that the capture history of the multievent model had eight primary occasions with two secondary surveys, and the capture history of the traditional model consisted of a series of 16 surveys. We used continuous-time formulations of the ecological process to allow direct comparison of ecological state transitions (mortality and infection dynamics) by modeling weekly time intervals [@conn2012; @ergon2018; @glennie2022], under the assumption that individuals did not change infection status more than once over this time. For both models, we kept parameters constant except for mortality hazards and recapture probabilities. We modeled the mortality hazard rates of infected individuals as functions of infection intensity, using the mortality hazard rate of uninfected individuals as an intercept, and included random survey effects for recapture. Mortality hazard rates are "apparent" because permanent emigration from the site was inseparable from mortality. For the multievent model, we used the method described above to estimate infection intensities from replicate qPCR runs. For the traditional multistate model, we used averaged positive qPCR runs as survey-specific individual intensities and modeled these as draws from a lognormal distribution. To get an average mortality hazard rate for infected individuals, we calculated ${\phi_2}_\mu = e^{\log(\phi_1) + \phi_\beta e^\mu}$.

We compared the full posterior distributions of parameters between the two models, and calculated comparisons as hazard ratios for hazard rates and odds ratios for probabilities. Additionally, we assessed MCMC efficiency following @ponisio2020 by comparing the effective sample size (ESS) over time for the parameters that were included in both models (excluding the pathogen detection parameters because they are not included in the traditional multistate model). We use the ESS/time for the slowest mixing parameter as a metric for MCMC performance.

\newpage

# Results

## Simulations

Robust design models showed good MCMC mixing and rapid convergence on posterior distributions that encompassed the simulation parameters (see *Supporting Information Appendix S1--S2*). Models with traditional sampling schemes, i.e., single surveys without secondary surveys, were unable to recover input parameters (*Supporting Information Appendix S3*). In exploring this problem, we found that even simple traditional multistate models suffered from weak parameter identifiability compared to robust design models, with low effective sample sizes and high prior-posterior overlap [*Supporting Information Appendix S4*, @gimenez2009]. Simulations also revealed that the true false-positive probabilities were accurately estimated, and fitting false-positive models to datasets simulated without false-positives yielded correct parameter estimation and near-zero false-positive probabilities (results not shown).

## Case study: *Mixophyes fleayi* (Fleay's barred frog)

The novel extended multievent model mixed well and all parameters rapidly converged. The probability of being infected with *Bd* at first capture ($\pi$) was estimated to be `r median(me$'pi.alpha')` \[`r hdi(me$'pi.alpha')`\] in the multievent model, the odds of which were approximately `r median(exp(qlogis(me$"pi.alpha") - qlogis(ms$"pi.alpha")))` times higher than estimated from the traditional multistate model assuming correct state assignment (`r median(ms$'pi.alpha')` \[`r hdi(ms$'pi.alpha')`\]), albeit with large uncertainty (@tbl-results, @fig-posteriors). Estimated apparent mortality rates ($\phi$) were similar between the two models, and we found no effects of *Bd* infection intensity on log mortality hazards (multievent: `r median(me$'phi.beta')` \[`r hdi(me$'phi.beta')`\], multistate: `r median(ms$'phi.beta')` \[`r hdi(ms$'phi.beta')`\]) (@tbl-results, @fig-posteriors). In the multievent model, the weekly hazard rate of gaining *Bd* ($\psi_{12}$) was `r median(me$'psi12.alpha')` \[`r hdi(me$'psi12.alpha')`\], approximately `r round(median(ms$"psi12.alpha" / me$"psi12.alpha"))` times lower than estimates from the multistate model (`r median(ms$'psi12.alpha')` \[`r hdi(ms$'psi12.alpha')`\]) (@tbl-results, @fig-posteriors). Similarly, the rate of clearing infection ($\psi_{21}$) in the multievent model (`r median(me$'psi21.alpha')` \[`r hdi(me$'psi21.alpha')`\]) was approximately `r round(median(ms$"psi21.alpha" / me$"psi21.alpha"))` times lower than estimated from the multistate model (`r median(ms$'psi21.alpha')` \[`r hdi(ms$'psi21.alpha')`\]) (@tbl-results, @fig-posteriors). Recapture probabilities ($p$) of infected individuals were estimated to be higher than for uninfected individuals, but this difference was more pronounced in the traditional multistate model (@tbl-results, @fig-posteriors). The average infection intensity of infected individuals ($e^\mu$) was estimated to be `r median(exp(me$'mu.alpha'))` \[`r hdi(exp(me$'mu.alpha'))`\] log~10~ gene copies per swab, with an estimated SD ($e^{\sigma_\mu}$) of `r median(exp(me$'mu.sigma[1]'))` \[`r hdi(exp(me$'mu.sigma[1]'))`\].

State misclassification in our study was substantial, particularly due to the sampling process (@tbl-results, @fig-det). The probability of detecting one log~10~ unit of *Bd* on an individual using a swab ($r_\delta$) was `r median(me$'r.delta')` \[`r hdi(me$'r.delta')`\], yielding a predicted `r 1 - (1 - median(me$'r.delta')) ^ exp(median(me$'mu.alpha'))` \[`r hdi(1 - (1 - me$'r.delta') ^ exp(me$'mu.alpha'))`\] probability of detecting *Bd* on a frog with an average infection intensity (@tbl-results, [@fig-det]a). By comparison, the probability of detecting one unit of *Bd* on an infected swab during a qPCR run ($r_\lambda$) was `r median(me$'r.lambda')` \[`r hdi(me$'r.lambda')`\], with a predicted `r 1 - (1 - median(me$'r.lambda')) ^ exp(median(me$'mu.alpha'))` \[`r hdi(hdi(1 - (1 - me$'r.lambda') ^ exp(me$'mu.alpha')))`\] probability of detecting *Bd* on an swab carrying an average infection intensity (@tbl-results, [@fig-det]b). Nevertheless, the sampling process featured lower measurement error ($\sigma_m$ = `r median(me$'mu.sigma[2]')` \[`r hdi(me$'mu.sigma[2]')`\]) than the diagnostic process ($\sigma_n$ = `r median(me$'mu.sigma[3]')` \[`r hdi(me$'mu.sigma[3]')`\]).

Estimated false-positive probabilities were considerable, particularly in the sampling process ($\delta_{21}$) with `r median(me$'delta21')` \[`r hdi(me$'delta21')`\] probability, and `r median(me$'lambda21')` \[`r hdi(me$'lambda21')`\] in the diagnostic process ($\lambda_{21}$) (@tbl-results). Ignoring false-positives in the sampling and diagnosic processes greatly influenced parameter estimates, with, for instance, the odds of entering with *Bd* nearly tripling to an estimate of `r median(me.nofp$'pi.alpha')` \[`r hdi(me.nofp$'pi.alpha')`\] (*Supporting Information Appendix S5*).

The novel multievent model ran approximately 30% faster than the traditional model, with approximately 60% higher ESS/time of the slowest mixing parameter (6.7/min) compared with traditional model (4.2/min).

\newpage

# Discussion

In this paper, we presented an extended multievent model that accounts for state uncertainty at multiple detection levels. The model uses underlying latent ecological processes that are identical to traditional multistate models (e.g., Arnason-Schwarz, Jolly-Seber), and relies on robust design survey efforts (replicate secondary surveys during primary occasions of assumed closure) to model the state assignment processes during detection "events" [@pollock1982; @pradel2005]. In our infectious disease-structured example, individuals captured more than once during a primary occasion facilitate the estimation of the pathogen detection process and false-positive probabilities on collected samples, analogously to occupancy models [@mackenzie2002; @royle2006]. Additional sources of state uncertainty, such as the diagnostic process that samples are subjected to, can be incorporated so that uncertainty at all levels of the observational hierarchy is propagated during inference on the ecological processes [@direnzo2018]. Finally, we illustrated the joint modeling of observed infection intensities to integrate them into relevant processes, like survival, state transitions, and pathogen detection [@lachish2012].

Using a mark-recapture dataset of an endangered Australian rainforest frog infected with the amphibian chytrid fungus *Bd*, we uncovered considerably different infection dynamics compared to traditional multistate models that assume no ambiguity in state assignment. Specifically, using the novel multievent model, the odds of individuals entering the study as infected with the pathogen---a reasonable proxy for infection prevalence in the unmarked population [@pradel2005]---were estimated to be approximately `r median(exp(qlogis(me$"pi.alpha") - qlogis(ms$"pi.alpha")))` higher, and rates of infection state transitions were estimated to be `r round(median(ms$"psi12.alpha" / me$"psi12.alpha"))`--`r round(median(ms$"psi21.alpha" / me$"psi21.alpha"))` times lower compared to the traditional multistate model. These results were not surprising in light of the pathogen detection process, where swabs had an average *Bd* detection probability of `r round((1 - (1 - median(me$'r.delta')) ^ exp(median(me$'mu.alpha')))*100,0)`%, and furthermore, featured a false-positive probability (`r round(median(me$'delta21')*100,0)`%) that is expected to bias inference [@mcclintock2010a]. The qPCR diagnostic process had better sensitivity, where even the lowest observed loads (\~ 100 gene copies per swab) were predicted to have `r round((1-(1-(1-(1-median(me$'r.lambda'))^2))^2)*100,0)`% chance of getting detected when running samples in duplicate. Indeed, our results indicate that replicating samples is more useful than replicating diagnostic runs because swab sampling devices can suffer from low sensitivity [@shin2014; @direnzo2018]. One caveat of our comparison was that due to the robust design formulation of the multievent model, primary occasions (pairs of consecutive weekly surveys) were assumed closed so infection state transitions could only occur between primaries, whereas in the multistate model, transitions could occur between all weeks. However, we postulate it is ecologically justified to assume individuals are not frequently gaining and clearing infections on weekly intervals.

The call to account for uncertainty in disease models is not novel, and we agree with @mcclintock2010 that addressing these sources of error are not "statistical fine points". When additional uncertainty is incorporated in models, precision in estimates is traded off against a reduction in bias, and we are generally of the view that this trade-off is worthwhile [@guillera-arroita2014]. It is worth considering the situation where false-negatives and false-positives are expected to be low (high sensitivity and specificity), where researchers may be tempted to assume correct state assignment and forego its explicit modeling. In this scenario, the reduction in precision of the estimates using the multievent model is expected to be minimal because the model will estimate a high degree of certainty in state assignment. Conversely, in the situation where sensitivity, specificity, or both are expected to be lower, more uncertainty will be introduced to the ecological process because state assignment is unreliable. Consequently, only when the problem of state assignment is pertinent does it significantly reduce the precision in estimates. Therefore, even in cases where state assignment errors are expected to be rare, we recommend the application of our multievent model if only to test underlying assumptions.

Our model requires surveys conducted with the robust design: more than one successive survey is required for every primary occasion, where individuals are sampled for infection with each capture. Attempts to fit the model to simulated single-survey data, where multiple samples were collected from each individual, revealed parameter identifiability issues. Exploration of this problem demonstrated that even traditional multistate models show poor MCMC mixing, low parameter effective samples sizes, and high prior-posterior overlap compared to robust design models, suggesting more general issues with traditional single-survey multistate mark-recapture designs (see *Supporting Information Appendix S4*). Although these models are routinely used in ecological studies, our results suggest that incorporating additional hierarchical levels of uncertainty makes these models more unstable. We recognize that robust design data may be perceived to be more costly due to increased sampling effort, but suggest that improved study design may avoid this cost altogether. Importantly, our results show that parameter estimation is much improved with the robust design, and we recommend it more generally when conducting mark-recapture studies. Since replicate samples of individuals are only collected from those individuals that are recaptured over several secondaries, the number of additional samples to be analysed is not expected to be excessive. However, as long as some individuals are recaptured over successive secondaries, these samples facilitate estimation of the false-negative and false-positive probabilities. Finally, the novel multievent model ran approximately 30% faster with 60% better efficiency [as measured by ESS/time of the slowest mixing parameter, @ponisio2020] than the traditional model, suggesting that with equal survey effort, incorporating additional uncertainty through robust design sampling does not result in excessive computational cost.

Modeling false-positives presents several challenges, including multimodality of the likelihood, parameter correlations, and inability to distinguish between heterogeneity in false- and true-positive probabilities [@miller2011]. Covariates can be implemented to disentangle true- and false-positives, and in our simulations, modeling the true-positive probabilities as functions of infection intensity was usually successful in avoiding incorrect multimodal solutions. To avoid any multimodality, applying constraints [e.g., false-positive probability \< true-positive probability, @royle2006] was required. One consideration regarding false-positives with diagnostic tests is to use informative priors, either from previous studies or manufacturer's instructions, to limit the parameter space. Finally, reversible jump MCMC could be employed to formally test for the inclusion of false-positive parameters [@green1995].

In conclusion, we have presented a model that incorporates state assignment errors at multiple levels of the detection process. Optional inclusion of observed infection intensities capitalizes on all of the available information to model heterogeneity in relevant parameters, such as survival and pathogen detection. Although our model was developed for infectious disease systems, the general structure can be applied to other types of HMMs where state assignment is uncertain and based on multiple detections. By providing code to simulate and analyze different model formulations, we have aimed to facilitate the application of our ideas to other models. We encourage a critical assessment of state assignment whenever this is relevant and to design studies that explicitly accommodate this uncertainty to produce less biased estimands of ecological processes.

\newpage

# Acknowledgments

Field surveys were conducted under New South Wales Scientific License 102444 with Southern Cross University Animal Care and Ethics Committee approval (Animal Research Authority 20-034). We are grateful for funding provided by the New South Wales Government's Saving our Species program, with particular thanks extended to Jill Smith and David Hunter. We are additionally thankful to David Newell for providing funding (under the Australian Research Council grant DP180101415) and supervision during the project. We thank Chris Paciorek for suggesting long format when incorporating infection intensities as data. We thank Graziella DiRenzo for providing feedback on an earlier version of the manuscript, and additionally thank Olivier Gimenez and Sina Mews for reviewing and contributing to improving the work. Any use of trade, firm, and product names is for descriptive purposes only and does not imply endorsement by the US government.

# Conflict of interest

The authors declare no conflict of interest.

# Author contributions

Matthijs Hollanders collected the data and conceived the model idea; Matthijs Hollanders and J. Andrew Royle developed the model; Matthijs Hollanders conducted the analyses; Matthijs Hollanders led the writing of the manuscript and J. Andrew Royle contributed critically to the drafts.

# Data availability

Data and code to analyse the *M. fleayi* data are available on Dryad (https://doi.org/10.5061/dryad.s7h44j19h); they are also available, along with appendix files, on GitHub.

Data used will be made available at Dryad and GitHub, along with all code.

# Supporting information

Code to simulate and analyze robust design capture histories are available in Appendix S1 (Arnason-Schwarz in continuous-time) and Appendix S2 (Jolly-Seber in discrete-time). Appendix S3 contains simulation and analysis for single-survey Arnason-Schwarz, revealing that this formulation is unable to recover input parameters. Simulations comparing model performance between robust design and single-survey multistate Arnason-Schwarz models is presented in Appendix S4. Parameter estimates from the multievent model with one or both false-positive probabilities excluded are presented in Appendix S5.

\newpage

# References

::: {#refs}
:::

\newpage

# Tables

\setstretch{1}

| **Symbol**           | **Definition**                                                                                                                                                    |
|--------------|----------------------------------------------------------|
| **Observed data**    |                                                                                                                                                                   |
| $\quad y_{itkl}$     | Diagnostic state of individual $i$, primary occasion $t$, (sample collected during) secondary survey $k$, and diagnostic run $l$                                  |
| $\quad x_{itkl}$     | Pathogen infection intensity of individual $i$, primary occasion $t$, (sample collected during) secondary survey $k$, and diagnostic run $l$                      |
|                      |                                                                                                                                                                   |
| **State variables**  |                                                                                                                                                                   |
| $\quad z_{it}$       | Ecological state of individual $i$ during primary occasion $t$                                                                                                    |
| $\quad o_{itk}$      | Observed state of individual $i$, primary occasion $t$, and (sample collected during) secondary survey $k$                                                        |
| $\quad m_{it}$       | Pathogen infection intensity of individual $i$ during primary occasion $t$                                                                                        |
| $\quad n_{itk}$      | Pathogen infection intensity of individual $i$, primary occasion $t$, and (sample collected during) secondary survey $k$                                          |
|                      |                                                                                                                                                                   |
| **Parameters**       |                                                                                                                                                                   |
| $\quad \pi$          | Probability of individual being in state 2 (infected with pathogen) when first captured                                                                           |
| $\quad \phi_1$       | Survival probability OR mortality hazard rate of individuals in state 1 (uninfected with pathogen) between time $t-1$ and time $t$                                |
| $\quad \phi_2$       | Survival probability OR mortality hazard rate of individuals in state 2 (infected with pathogen) between time $t-1$ and time $t$                                  |
| $\quad \psi_{12}$    | Probability OR hazard rate of transitioning from state 1 (uninfected) to state 2 (infected) between time $t-1$ and time $t$                                       |
| $\quad \psi_{21}$    | Probability OR hazard rate of transitioning from state 2 (infected) to state 1 (uninfected) between time $t-1$ and time $t$                                       |
| $\quad p_1$          | Recapture probability of individuals in state 1 (uninfected with pathogen)                                                                                        |
| $\quad p_2$          | Recapture probability of individuals in state 2 (infected with pathogen)                                                                                          |
| $\quad \delta_{22}$  | Probability of detecting pathogen on a sample from an infected individual (true-positive, sampling sensitivity)                                                   |
| $\quad r_\delta$     | Probability of detecting one unit of pathogen on a sample when ${\delta_{22}}_{it} = 1 - (1 - r_\delta)^{m_{it}}$                                                 |
| $\quad \delta_{21}$  | Probability of detecting pathogen on a sample from an uninfected individual (false-positive), where the inverse is the sampling specificity (true-negative)       |
| $\quad \lambda_{22}$ | Probability of detecting pathogen in a diagnostic run from an infected sample (true-positive, diagnostic sensitivity)                                             |
| $\quad r_\lambda$    | Probability of detecting one unit of a pathogen in a diagnostic run when ${\lambda_{22}}_{itk} = 1 - (1 - r_\lambda)^{n_{itk}}$                                   |
| $\quad \lambda_{21}$ | Probability of detecting pathogen in a diagnostic run from an uninfected sample (false-positive), where the inverse is the diagnostic specificity (true-negative) |
| $\quad \mu$          | (Log) average of the population pathogen infection intensity                                                                                                      |
| $\quad \sigma_{\mu}$ | (Log) SD of the population pathogen infection intensity                                                                                                           |
| $\quad \sigma_{m}$   | Measurement error (SD) of the pathogen sampling process                                                                                                           |
| $\quad \sigma_{n}$   | Measurement error (SD) of the pathogen diagnostic process                                                                                                         |

: Observed data, latent state variables, and parameters of the extended multievent model, illustrated with an infectious disease-structured Arnason-Schwarz example. {#tbl-parameters} {tbl-colwidths="\[20,80\]"}

\newpage

|                        | **Multievent**                    |                                    | **Multistate**                 |                                 | **Comparison**                                             |                                                             |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| **Parameter**          | **Median**                        | **95% HPDI**                       | **Median**                     | **95% HPDI**                    | **Median**                                                 | **95% HPDI**                                                |
| Hazard rates           |                                   |                                    |                                |                                 |                                                            |                                                             |
| $\quad \phi_1$         | `r median(me$phi1.alpha)`         | \[`r hdi(me$phi1.alpha)`\]         | `r median(ms$phi1.alpha)`      | \[`r hdi(ms$phi1.alpha)`\]      | `r median(ms$phi1.alpha / me$phi1.alpha)`                  | \[`r hdi(ms$phi1.alpha / me$phi1.alpha)`\]                  |
| $\quad \phi_\beta$     | `r median(me$phi.beta)`           | \[`r hdi(me$phi.beta)`\]           | `r median(ms$phi.beta)`        | \[`r hdi(ms$phi.beta)`\]        | `r median(ms$phi.beta - me$phi.beta)`                      | \[`r hdi(ms$phi.beta - me$phi.beta)`\]                      |
| $\quad \psi_{12}$      | `r median(me$psi12.alpha)`        | \[`r hdi(me$psi12.alpha)`\]        | `r median(ms$psi12.alpha)`     | \[`r hdi(ms$psi12.alpha)`\]     | `r median(ms$psi12.alpha / me$psi12.alpha)`                | \[`r hdi(ms$psi12.alpha / me$psi12.alpha)`\]                |
| $\quad \psi_{21}$      | `r median(me$psi21.alpha)`        | \[`r hdi(me$psi21.alpha)`\]        | `r median(ms$psi21.alpha)`     | \[`r hdi(ms$psi21.alpha)`\]     | `r median(ms$psi21.alpha / me$psi21.alpha)`                | \[`r hdi(ms$psi21.alpha / me$psi21.alpha)`\]                |
|                        |                                   |                                    |                                |                                 |                                                            |                                                             |
| Probabilities          |                                   |                                    |                                |                                 |                                                            |                                                             |
| $\quad \pi$            | `r median(me$pi.alpha)`           | \[`r hdi(me$pi.alpha)`\]           | `r median(ms$pi.alpha)`        | \[`r hdi(ms$pi.alpha)`\]        | `r median(exp(qlogis(ms$pi.alpha) - qlogis(me$pi.alpha)))` | \[`r hdi(exp(qlogis(ms$pi.alpha) - qlogis(me$pi.alpha)))`\] |
| $\quad p_1$            | `r median(me$p1.alpha)`           | \[`r hdi(me$p1.alpha)`\]           | `r median(ms$p1.alpha)`        | \[`r hdi(ms$p1.alpha)`\]        | `r median(exp(qlogis(ms$p1.alpha) - qlogis(me$p1.alpha)))` | \[`r hdi(exp(qlogis(ms$p1.alpha) - qlogis(me$p1.alpha)))`\] |
| $\quad p_2$            | `r median(me$p2.alpha)`           | \[`r hdi(me$p2.alpha)`\]           | `r median(ms$p2.alpha)`        | \[`r hdi(ms$p2.alpha)`\]        | `r median(exp(qlogis(ms$p2.alpha) - qlogis(me$p2.alpha)))` | \[`r hdi(exp(qlogis(ms$p2.alpha) - qlogis(me$p2.alpha)))`\] |
| $\quad p_\sigma$       | `r median(me$p.sigma)`            | \[`r hdi(me$p.sigma)`\]            | `r median(ms$p.sigma)`         | \[`r hdi(ms$p.sigma)`\]         | `r median(ms$p.sigma - me$p.sigma)`                        | \[`r hdi(ms$p.sigma - me$p.sigma)`\]                        |
| $\quad r_\delta$       | `r median(me$r.delta)`            | \[`r hdi(me$r.delta)`\]            |                                |                                 |                                                            |                                                             |
| $\quad \delta_{21}$    | `r median(me$delta21)`            | \[`r hdi(me$delta21)`\]            |                                |                                 |                                                            |                                                             |
| $\quad r_\lambda$      | `r median(me$r.lambda)`           | \[`r hdi(me$r.lambda)`\]           |                                |                                 |                                                            |                                                             |
| $\quad \lambda_{21}$   | `r median(me$lambda21)`           | \[`r hdi(me$lambda21)`\]           |                                |                                 |                                                            |                                                             |
|                        |                                   |                                    |                                |                                 |                                                            |                                                             |
| Infection intensity    |                                   |                                    |                                |                                 |                                                            |                                                             |
| $\quad e^\mu$          | `r median(exp(me$mu.alpha))`      | \[`r hdi(exp(me$mu.alpha))`\]      | `r median(exp(ms$mu.alpha))`   | \[`r hdi(exp(ms$mu.alpha))`\]   | `r median(exp(ms$mu.alpha) - exp(me$mu.alpha))`            | \[`r hdi(exp(ms$mu.alpha) - exp(me$mu.alpha))`\]            |
| $\quad e^{\sigma_\mu}$ | `r median(exp(me$"mu.sigma[1]"))` | \[`r hdi(exp(me$"mu.sigma[1]"))`\] | `r median(exp(ms$"mu.sigma"))` | \[`r hdi(exp(ms$"mu.sigma"))`\] | `r median(exp(ms$"mu.sigma") - exp(me$"mu.sigma[1]"))`     | \[`r hdi(exp(ms$"mu.sigma") - exp(me$"mu.sigma[1]"))`\]     |
| $\quad \sigma_m$       | `r median(me$"mu.sigma[2]")`      | \[`r hdi(me$"mu.sigma[2]")`\]      |                                |                                 |                                                            |                                                             |
| $\quad \sigma_n$       | `r median(me$"mu.sigma[3]")`      | \[`r hdi(me$"mu.sigma[3]")`\]      |                                |                                 |                                                            |                                                             |

: Posterior distributions (median and 95% HPDI) of parameters estimated from the novel extended multievent model and the traditional multistate Arnason-Schwarz model fitted to the *M. fleayi* data. Parameter definitions are provided in @tbl-parameters, $\phi_\beta$ is the effect of infection intensity on the log apparent mortality hazard rate of infected individuals, and $p_\sigma$ is the SD of the random survey effect on recapture log odds. We compared the full posterior distributions of parameters between the two models, and calculated hazard ratios for hazard rates, odds ratios for probabilities, and the differences between $\phi_\beta$, $p_\sigma$, and the infection intensity parameters, using results from the multievent model as baseline (e.g., $\frac{\phi_1^\text{Multistate}}{\phi_1^\text{Multievent}}$). {#tbl-results} {tbl-colwidths="\[22,10,16,10,16,10,16\]"}

\setstretch{2}

\newpage

# Figures

![Posterior distributions (median and 95% HPDI) of parameters estimated from the novel multievent model and the traditional multistate Arnason-Schwarz model fitted to the *M. fleayi* data (@tbl-parameters). Hazard rates (apparent mortality and infection state transitions) are on weekly time scales. The mortality rate of infected individuals was derived from posterior samples as $\phi_2 = e^{\log(\phi_1) + \phi_\beta e^\mu}$.](figs/posteriors.jpg){#fig-posteriors}

\newpage

![Predicted pathogen detection probabilities (median and 95% equal-tailed interval) of the extended multievent model. **a** The probability of detecting *Bd* on a swab from an infected individual as a function of individual infection intensity (log~10~ gene copies per swab), predicted using $\delta_{22} = 1 - (1 - r_\delta) ^ m$. The rugplot shows estimated individual intensities from individuals returning at least one positive qPCR run. **b** The probability of detecting *Bd* in a diagnostic run from an infected swab as a function of sample infection intensity (log~10~ gene copies per swab), predicted using $\lambda_{22} = 1 - (1 - r_\lambda) ^ n$. The rugplot shows estimated sample intensities from samples returning at least one positive qPCR run.](figs/fig-det.jpg){#fig-det}
